package samefinallproject;


import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.Dimension;
import java.awt.FlowLayout;
import static java.awt.FlowLayout.CENTER;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;

public class NewJFrame extends javax.swing.JFrame {
GridBagLayout layout=new GridBagLayout();
    panel1 p1;
    panel2 p2;
    panel3 p3;
    panel4 p4 ;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setResizable(false);
        initComponents();
        p1=new panel1();
        p2=new panel2();
        p3=new panel3();
        p4 = new panel4();
        dynamicpanel.setLayout(layout);
        GridBagConstraints c=new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        dynamicpanel.add(p1,c);
        c.gridx=0;
        c.gridy=0;
        dynamicpanel.add(p2,c);
        dynamicpanel.add(p3,c);
        dynamicpanel.add(p4,c);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        dynamicpanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jButton1.setBackground(new java.awt.Color(150, 182, 203));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Add Teacher");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setMaximumSize(new java.awt.Dimension(131, 35));
        jButton1.setMinimumSize(new java.awt.Dimension(131, 35));
        jButton1.setPreferredSize(new java.awt.Dimension(137, 35));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dynamicpanel.setBackground(new java.awt.Color(204, 204, 204));
        dynamicpanel.setPreferredSize(new java.awt.Dimension(700, 0));

        javax.swing.GroupLayout dynamicpanelLayout = new javax.swing.GroupLayout(dynamicpanel);
        dynamicpanel.setLayout(dynamicpanelLayout);
        dynamicpanelLayout.setHorizontalGroup(
            dynamicpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        dynamicpanelLayout.setVerticalGroup(
            dynamicpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton2.setBackground(new java.awt.Color(150, 182, 203));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("Add Courses");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(150, 182, 203));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("Add Room");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setPreferredSize(new java.awt.Dimension(137, 35));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(150, 182, 203));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setText("Display Table");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setPreferredSize(new java.awt.Dimension(137, 35));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dynamicpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dynamicpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JFrame JF = new JFrame("DisplayTable");
        JF.setLayout(new FlowLayout(CENTER, 10, 20));
        JF.setSize(950, 510);
        JF.setResizable(false);
        
        ArrayList<Teacher> teachers =new ArrayList();
        ArrayList<Room> Rooms = new ArrayList() ;
        ArrayList<Course> Courses = new ArrayList() ;
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=TimeTable;integratedSecurity=true";
            Connection con = DriverManager.getConnection(url);
            if(con.isValid(100))
            {

                String sql = "select * from Teacher";
                PreparedStatement pstw = con.prepareStatement(sql);
                ResultSet rs = pstw.executeQuery();
                while(rs.next())
                {
                    Teacher t = new Teacher() ;
                    t.setID(rs.getString(1));
                    t.setPhone(rs.getString(2));
                    t.setEmail(rs.getNString(3));
                    teachers.add(t);
                }
                String sql2 = "select * from Class_Room";
                PreparedStatement pst = con.prepareStatement(sql2);
                ResultSet rss = pst.executeQuery();
                while(rss.next())
                {
                    Classroom c = new Classroom();
                    c.setName(rss.getString(2));
                    Rooms.add(c) ;
                }
                String sql3 = "select * from Laboratory";
                PreparedStatement ps = con.prepareStatement(sql3);
                ResultSet rsss = ps.executeQuery();
                while(rsss.next())
                {
                    Laboratoty l = new Laboratoty();
                    l.setName(rsss.getString(2));
                    Rooms.add(l) ;
                }
                String sql4 = "select * from Course";
                PreparedStatement p = con.prepareStatement(sql4);
                ResultSet rssss = p.executeQuery();
                while(rssss.next())
                {
                    Course c = new  Course();
                    c.setName(rssss.getString(2));
                    Courses.add(c) ;
                }
            }

            con.close();
        }
        catch(ClassNotFoundException e){

            JOptionPane.showMessageDialog(null, "NOOOOOOOO");
        } catch (SQLException ex) {
        Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
        
     
        
        JComboBox teacherIDS = new JComboBox() ;
            teacherIDS.setSelectedItem(" ");
            teacherIDS.setSelectedIndex(-1);
            JF.add(teacherIDS);
            Iterator<Teacher> teacherIterator = teachers.iterator();
            while(teacherIterator.hasNext()){
                teacherIDS.addItem(teacherIterator.next().getID());
            }
            teacherIDS.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                
                SeparateTable s = new SeparateTable(teacherIDS.getSelectedItem().toString());
                s.setExtendedState(JFrame.MAXIMIZED_BOTH);
                s.addWindowListener(new WindowAdapter() {
                    public void windowClosing(WindowEvent e){
                        System.exit(0);
                    }
});
            }
        });
            
            JComboBox Roomss = new JComboBox() ;
            Roomss.setSelectedItem(" ");
            Roomss.setSelectedIndex(-1);
            JF.add(Roomss);
            Iterator<Room> roomIterator = Rooms.iterator();
            while(roomIterator.hasNext()){
                Roomss.addItem(roomIterator.next().getName());
            }
            Roomss.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                SeparateTableRoom s = new SeparateTableRoom(Roomss.getSelectedItem().toString());
                s.setExtendedState(JFrame.MAXIMIZED_BOTH);
                s.addWindowListener(new WindowAdapter() {
                    public void windowClosing(WindowEvent e){
                        System.exit(0);
                    }
});
            }
        });
            
            JComboBox courseName = new JComboBox() ;
            courseName.setSelectedItem(" ");
            courseName.setSelectedIndex(-1);
            JF.add(courseName);
            Iterator<Course> courseIterator = Courses.iterator();
            while(courseIterator.hasNext()){
                courseName.addItem(courseIterator.next().getName());
            }
            courseName.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                SeparateTableCourse s = new SeparateTableCourse(courseName.getSelectedItem().toString());
                s.setExtendedState(JFrame.MAXIMIZED_BOTH);
                s.addWindowListener(new WindowAdapter() {
                    public void windowClosing(WindowEvent e){
                        System.exit(0);
                    }
});
            }
        });
            JButton BTN_table = new JButton("Show Complete Table");
                    BTN_table.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                                    JTextAreaTable frame = new JTextAreaTable();
        
        frame.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        frame.addWindowListener(new WindowAdapter() {
        public void windowClosing(WindowEvent e) {
        System.exit(0);
      }
    });
                        }
                    });

                    JF.add(BTN_table);
            
        
   
            
        JF.setVisible(true);
        JF.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            

                        

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dynamicpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
