package samefinallproject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author egypt2
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
public class panel3 extends javax.swing.JPanel {

    /**
     * Creates new form panel3
     */
    public panel3() {
        initComponents();
        if(this.getComponentCount() > 1){
            // Remove old component if found
            for(int i = 1; this.getComponentCount() > 1;){
                this.remove(i);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(700, 596));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setAlignmentX(5.0F);
        jPanel1.setAlignmentY(5.0F);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Enter Number of Rooms");

        jTextField7.setToolTipText("");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(57, 57, 57)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(468, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(490, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
        
        if(this.getComponentCount() > 1){
            // Remove old component if found
            for(int i = 1; this.getComponentCount() > 1;){
                this.remove(i);
            }
        }
        
        // Get and parse the number of lectures from ComboBox
        int num = Integer.parseInt(jTextField7.getText());        
        
        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        
        for (int i = 1; i <= num; i++) {
            // New panel to hold the JLabels and JTextField
            JPanel lecturesPanel = new JPanel(new GridBagLayout());
            
            // To be Horziantal Alignment
            GridBagConstraints gbc = new GridBagConstraints();
            gbc.anchor = GridBagConstraints.NORTH;
            
            lecturesPanel.setBorder(BorderFactory.createTitledBorder("Room " + i));
            
            JPanel teacherPanel = new JPanel(new FlowLayout());
            JLabel teacherID = new JLabel("Room Name");
            JTextField RoomTextField = new JTextField("          ");
            
            teacherPanel.add(teacherID);
            teacherPanel.add(RoomTextField);
            
            JPanel roomPanel = new JPanel(new FlowLayout());
            JLabel room = new JLabel("Room Type");
            JComboBox roomcombobox = new JComboBox() ;
            roomcombobox.addItem("Laboratory");
            roomcombobox.addItem("Classroom");
                  
            JButton AddButton = new JButton();
            AddButton.setText("Add"); 
            
            roomPanel.add(room);
            roomPanel.add(roomcombobox);
            roomPanel.add(AddButton);
            
            lecturesPanel.add(teacherPanel, gbc);
            lecturesPanel.add(roomPanel, gbc);
            
            this.add(lecturesPanel);
            AddButton.addActionListener((ActionEvent e) -> {
                String roomname = RoomTextField.getText() ;
                String roomtype = String.valueOf(roomcombobox.getSelectedItem());
            try{
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url="jdbc:sqlserver://localhost:1433;databaseName=TimeTable;integratedSecurity=true";
                Connection con = DriverManager.getConnection(url);
                if(con.isValid(100))
                    {
                        if("Classroom".equals(roomtype)){
                        String query = "insert into Class_Room(Class_Romm_Name)values(?)" ;
                        PreparedStatement pst = con.prepareStatement(query) ;
                        pst.setString(1, roomname);
                        pst.executeUpdate() ;
                        }
                        else if("Laboratory".equals(roomtype)){
                        String query = "insert into Laboratory(Laboratory_Name)values(?)" ;
                        PreparedStatement pst = con.prepareStatement(query) ;
                        pst.setString(1, roomname);
                        pst.executeUpdate() ;
                        }
                    }
        
        con.close();
        }
        catch(ClassNotFoundException | SQLException a){
        
        JOptionPane.showMessageDialog(null, a);
        }
            });

        }
        getParent().validate();

    }//GEN-LAST:event_jTextField7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
